### PR TITLE
feat: remove course controller

### PR DESCRIPTION
**Pull request by tomwim**
### Description
Remove course controller and menu in favor of https://github.com/Innoactive/Basic-UI-Component/pull/1

### Type of change
- [X] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] This change requires a documentation update

### How Has This Been Tested?
Get https://github.com/Innoactive/Basic-UI-Component/pull/1
and https://github.com/Innoactive/Creator-Pro/pull/13

### CODE REVIEW

**Review by Gusinuhe — DISMISSED** [review]

**Comment by Gusinuhe** [comment]
Scenes that previously had a `[COURSE_CONTROLLER]` are now broken and no training course could be played without setting them up again.

image

**Comment by Gusinuhe** [comment]
> Scenes that previously had a `[COURSE_CONTROLLER]` are now broken and no training course could be played (no play button) without setting them up again.
> 
> image

This does not happen when importing everything from scratch

**Comment by tomwim** [comment]
Any ideas how to prevent/fix this @Gusinuhe ?

**Comment by Gusinuhe** [comment]
> Any ideas how to prevent/fix this @Gusinuhe ?

I'm gonna test how critical this is by updating a project from an older version to this one hopefully, the issue is solved automatically.

The thing is that when it happened the first time, I cloned everything in develop, imported it to Unity, and then started to checkout individually each branch, this repo was the last one so I did have two [COURSE_CONTROLLER] in the project and that could actually be the reason why it was missing the first time.

**Comment by SimonTheSourcerer** [comment]
tested this earlier on and it work so far, but my instance of the prefab was not linked earlier on. So the problem gustavo mentioned was not tested.

**Comment by Gusinuhe** [comment]
Tested again, the issue is not present when "upgrading" the creator, it only appears when switching manually the branches on a very specific combination. This should not be an issue that any user would face.

**Review by Gusinuhe — APPROVED** [review]

**Pull request merged**
