### PR TITLE
feat(validation): added validation attributes to behaviors

### PR DESCRIPTION
**Pull request by SimonTheSourcerer**
### Description
Made some behavior fields optional

### CODE REVIEW

**Review by Gusinuhe — APPROVED** [review]
👌

**Review by Maxsiom — CHANGES_REQUESTED** [review]
image

`Position Provider` should be optional. It is only needed, when `Spawn Above Trainee` is not checked.

**Comment by tomwim** [comment]
> image
> 
> `Position Provider` should be optional. It is only needed, when `Spawn Above Trainee` is not checked.

So it is actually conditional-optional? 🤔

**Comment by Maxsiom** [comment]
> So it is actually conditional-optional? 🤔

Yes. It's a bit inconvenient but it was made that way before we had this drag & drop system for training scene objects. Beforehand, it was just a field for the unique name which could be empty.

**Review by Gusinuhe — CHANGES_REQUESTED** [review]
Is this still part of the validation system? It is not mentioned in the original PR https://github.com/Innoactive/Creator/pull/189.

If so, it is missing the defined symbols.

**Comment by SimonTheSourcerer** [comment]
should be part, can be adapted later.

**Review by Gusinuhe — APPROVED** [review]

**Review by Maxsiom — APPROVED** [review]

**Review by Maxsiom — APPROVED** [review]

**Pull request merged**
