### PR TITLE
The Default scene was updated TRNG-907

### PR DESCRIPTION
**Pull request by Gusinuhe**
### Description

- The Environment01v was renamed to Environment
- The teleport interactions were updated to their newer signatures.

### Relates

- https://github.com/Innoactive/Creator-Examples/pull/27

### CODE REVIEW

**Review by vued — COMMENTED** [review]
This does not automatically update the scenes used in advanced examples, correct?
Can we update them as well, please?

**Comment by Gusinuhe** [comment]
> This does not automatically update the scenes used in advanced examples, correct?
> Can we update them as well, please?

It doesn't fortunately, those are already updated 👍

**Comment by vued** [comment]
> > This does not automatically update the scenes used in advanced examples, correct?
> > Can we update them as well, please?
> 
> It doesn't fortunately, those are already updated 👍 ... at least the teleport events, I'll update the name too.

Please also make sure that the folder in Assets\Innoactive\Creator\Base-Template\Resources\AdvancedEnvironment\StaticAssets is renamed accordingly as well. 
In addition to the prefab, the mesh also has the name "Environment01v".

**Comment by Gusinuhe** [comment]
> > > This does not automatically update the scenes used in advanced examples, correct?
> > > Can we update them as well, please?
> > 
> > 
> > It doesn't fortunately, those are already updated 👍 ... at least the teleport events, I'll update the name too.
> 
> Please also make sure that the folder in Assets\Innoactive\Creator\Base-Template\Resources\AdvancedEnvironment\StaticAssets is renamed accordingly as well.
> In addition to the prefab, the mesh also has the name "Environment01v".

The mesh and the prefab were renamed in this PR, the examples can be found here: https://github.com/Innoactive/Creator-Examples/pull/27

**Review by tomwim — CHANGES_REQUESTED** [review]

**Comment by tomwim** [comment]
Hijacked this PR and removed all Environment stuff and moved it into the Examples. Also removed Default and Simplified scenes. Moved the fonts into Basic UI

PRs:
https://github.com/Innoactive/Creator-Examples/pull/27
https://github.com/Innoactive/Basic-UI-Component/pull/22

**Review by vued — APPROVED** [review]

**Review by Luphoxa — APPROVED** [review]
Test Approval

**Review by tomwim — APPROVED** [review]

**Pull request merged**
